twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        hotboxservice: '@App\Service\HotBoxService'
        settings: '@App\Service\SettingsService'
when@test:
    twig:
        strict_variables: true
